# Generated by Django 5.0 on 2025-04-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('econ', 'Economics'), ('chem', 'Chemistry'), ('phy', 'Physics'), ('math', 'Maths')], default='econ', max_length=4),
        ),
    ]
